/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Status */
        get: operations["data_status_v1_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["list_favorites_v1_me_favorites_get"];
        put?: never;
        /** Save Favorite */
        post: operations["save_favorite_v1_me_favorites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/favorites/{favorite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Favorite */
        delete: operations["delete_favorite_v1_me_favorites__favorite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_v1_me_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_v1_me_preferences_get"];
        /** Update Preferences */
        put: operations["update_preferences_v1_me_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mobility/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mobility Vehicles */
        get: operations["mobility_vehicles_v1_mobility_vehicles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/routes/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Route */
        post: operations["plan_route_v1_routes_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/routes/reroute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reroute */
        post: operations["reroute_v1_routes_reroute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse Search */
        get: operations["reverse_search_v1_search_reverse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessibilityPreferences */
        AccessibilityPreferences: {
            /**
             * Avoid Stairs
             * @default false
             */
            avoid_stairs: boolean;
            /**
             * Maximum Carry Distance M
             * @default 500
             */
            maximum_carry_distance_m: number;
            /**
             * Require Step Free
             * @default false
             */
            require_step_free: boolean;
        };
        /** Coordinate */
        Coordinate: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /**
         * DataConfidence
         * @enum {string}
         */
        DataConfidence: "high" | "medium" | "low" | "unknown";
        /** DataQuality */
        DataQuality: {
            confidence: components["schemas"]["DataConfidence"];
            /** Dataset Versions */
            dataset_versions?: {
                [key: string]: string;
            };
            /**
             * Realtime Transit
             * @default false
             */
            realtime_transit: boolean;
            /**
             * Scheduled Transit
             * @default true
             */
            scheduled_transit: boolean;
            /** Shade Sources */
            shade_sources?: string[];
            /** Warnings */
            warnings?: string[];
        };
        /** DataStatus */
        DataStatus: {
            /** Coverage */
            coverage: string;
            /** Data Version */
            data_version: string;
            /** Engine Profile */
            engine_profile: string;
            /** Feeds */
            feeds: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Warmed */
            warmed: boolean;
        };
        /** Favorite */
        Favorite: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            place: components["schemas"]["Place"];
        };
        /** FavoriteCreate */
        FavoriteCreate: {
            /** Label */
            label: string;
            place: components["schemas"]["Place"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            destination: components["schemas"]["Place"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Id */
            id: string;
            mode: components["schemas"]["TravelMode"];
            /** Origin Label */
            origin_label: string;
        };
        /**
         * Locale
         * @enum {string}
         */
        Locale: "he" | "en";
        /** Maneuver */
        Maneuver: {
            coordinate: components["schemas"]["Coordinate"];
            /** Distance M */
            distance_m: number;
            /** Duration S */
            duration_s: number;
            /** Geometry Index */
            geometry_index: number;
            /** Id */
            id: string;
            /** Instruction Key */
            instruction_key: string;
            /** Instruction Text */
            instruction_text?: string | null;
            /** Modifier */
            modifier?: string | null;
            /** Street Name */
            street_name?: string | null;
        };
        /** MobilityResponse */
        MobilityResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Vehicles */
            vehicles: components["schemas"]["MobilityVehicle"][];
            /** Warnings */
            warnings?: string[];
        };
        /** MobilityVehicle */
        MobilityVehicle: {
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Battery Percent */
            battery_percent?: number | null;
            coordinate: components["schemas"]["Coordinate"];
            /** Deep Link */
            deep_link?: string | null;
            /** Id */
            id: string;
            kind: components["schemas"]["VehicleKind"];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Provider */
            provider: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /** Place */
        Place: {
            /** Category */
            category: string;
            /** @default high */
            confidence: components["schemas"]["DataConfidence"];
            coordinate: components["schemas"]["Coordinate"];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Name He */
            name_he?: string | null;
            /** Subtitle */
            subtitle?: string | null;
        };
        /** RentalDetails */
        RentalDetails: {
            /** Battery Percent */
            battery_percent?: number | null;
            /** Deep Link */
            deep_link?: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Provider */
            provider: string;
            /** Vehicle Id */
            vehicle_id: string;
        };
        /** RerouteRequest */
        RerouteRequest: {
            accessibility?: components["schemas"]["AccessibilityPreferences"];
            /** Accuracy M */
            accuracy_m?: number | null;
            constraints?: components["schemas"]["RouteConstraints"];
            current_position: components["schemas"]["Coordinate"];
            /** Depart At */
            depart_at?: string | null;
            destination: components["schemas"]["Coordinate"];
            /** Heading Degrees */
            heading_degrees?: number | null;
            /** @default he */
            locale: components["schemas"]["Locale"];
            /** @default walk */
            mode: components["schemas"]["TravelMode"];
            /** Original Route Id */
            original_route_id?: string | null;
            /** @default fastest */
            preference: components["schemas"]["RoutePreference"];
            vehicle?: components["schemas"]["VehicleProfile"];
        };
        /** RouteAlternative */
        RouteAlternative: {
            /** Annotations */
            annotations: components["schemas"]["SegmentAnnotation"][];
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Departure At
             * Format: date-time
             */
            departure_at: string;
            /** Encoded Polyline */
            encoded_polyline: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /** Id */
            id: string;
            /** Label Key */
            label_key: string;
            /** Legs */
            legs: components["schemas"]["RouteLeg"][];
            /** Maneuvers */
            maneuvers: components["schemas"]["Maneuver"][];
            metrics: components["schemas"]["RouteMetrics"];
            quality: components["schemas"]["DataQuality"];
            /** Warnings */
            warnings?: string[];
        };
        /** RouteConstraints */
        RouteConstraints: {
            /**
             * Allow Low Confidence Crossings
             * @default false
             */
            allow_low_confidence_crossings: boolean;
            /** Maximum Distance Detour Percent */
            maximum_distance_detour_percent?: number | null;
            /** Maximum Time Detour Percent */
            maximum_time_detour_percent?: number | null;
        };
        /** RouteLeg */
        RouteLeg: {
            /** Annotations */
            annotations?: components["schemas"]["SegmentAnnotation"][];
            /** Distance M */
            distance_m: number;
            /** Duration S */
            duration_s: number;
            /** Encoded Polyline */
            encoded_polyline: string;
            /** From Name */
            from_name: string;
            /** Maneuvers */
            maneuvers?: components["schemas"]["Maneuver"][];
            mode: components["schemas"]["TravelMode"];
            rental?: components["schemas"]["RentalDetails"] | null;
            /** To Name */
            to_name: string;
            transit?: components["schemas"]["TransitDetails"] | null;
        };
        /** RouteMetrics */
        RouteMetrics: {
            /**
             * Cycling Distance M
             * @default 0
             */
            cycling_distance_m: number;
            /**
             * Detour Distance Percent
             * @default 0
             */
            detour_distance_percent: number;
            /**
             * Detour Time Percent
             * @default 0
             */
            detour_time_percent: number;
            /** Distance M */
            distance_m: number;
            /** Duration S */
            duration_s: number;
            /** High Confidence Shade Fraction */
            high_confidence_shade_fraction?: number | null;
            /** Shade Fraction */
            shade_fraction?: number | null;
            /** Signals Avoided */
            signals_avoided?: number | null;
            /** Sun Exposure Minutes */
            sun_exposure_minutes?: number | null;
            /** Traffic Signals */
            traffic_signals?: number | null;
            /**
             * Transfers
             * @default 0
             */
            transfers: number;
            /**
             * Walking Distance M
             * @default 0
             */
            walking_distance_m: number;
        };
        /** RoutePlanRequest */
        RoutePlanRequest: {
            accessibility?: components["schemas"]["AccessibilityPreferences"];
            /** Arrive By */
            arrive_by?: string | null;
            constraints?: components["schemas"]["RouteConstraints"];
            /** Depart At */
            depart_at?: string | null;
            destination: components["schemas"]["Coordinate"];
            /** @default he */
            locale: components["schemas"]["Locale"];
            /** @default walk */
            mode: components["schemas"]["TravelMode"];
            origin: components["schemas"]["Coordinate"];
            /** @default fastest */
            preference: components["schemas"]["RoutePreference"];
            vehicle?: components["schemas"]["VehicleProfile"];
        };
        /** RoutePlanResponse */
        RoutePlanResponse: {
            /** Data Version */
            data_version: string;
            /** Engine Profile */
            engine_profile: string;
            /** Request Id */
            request_id: string;
            /** Routes */
            routes: components["schemas"]["RouteAlternative"][];
        };
        /**
         * RoutePreference
         * @enum {string}
         */
        RoutePreference: "fastest" | "balanced_shade" | "maximum_shade" | "fewer_lights" | "safer_streets" | "fewer_transfers";
        /** SearchResponse */
        SearchResponse: {
            /** Data Version */
            data_version: string;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["Place"][];
        };
        /** SegmentAnnotation */
        SegmentAnnotation: {
            /** Classification */
            classification: string;
            /** @default unknown */
            confidence: components["schemas"]["DataConfidence"];
            /** Crossing Kind */
            crossing_kind?: string | null;
            /** End Index */
            end_index: number;
            /** Selected Side */
            selected_side?: string | null;
            /** Shade Fraction */
            shade_fraction?: number | null;
            /** Start Index */
            start_index: number;
        };
        /** TransitDetails */
        TransitDetails: {
            /** Agency */
            agency: string;
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
            /**
             * Departure At
             * Format: date-time
             */
            departure_at: string;
            /** Headsign */
            headsign: string;
            /**
             * Realtime
             * @default false
             */
            realtime: boolean;
            /** Route Short Name */
            route_short_name: string;
            /** Stops */
            stops: number;
            /** Vehicle Rule Source */
            vehicle_rule_source?: string | null;
        };
        /**
         * TravelMode
         * @enum {string}
         */
        TravelMode: "walk" | "bike" | "scooter" | "car" | "motorcycle" | "truck" | "transit" | "bike_transit" | "scooter_transit" | "rental_transit";
        /** UserPreferences */
        UserPreferences: {
            /** @default walk */
            default_mode: components["schemas"]["TravelMode"];
            /** @default balanced_shade */
            default_walk_preference: components["schemas"]["RoutePreference"];
            /**
             * History Enabled
             * @default false
             */
            history_enabled: boolean;
            /** @default he */
            locale: components["schemas"]["Locale"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VehicleKind
         * @enum {string}
         */
        VehicleKind: "none" | "full_size_bike" | "folding_bike" | "personal_scooter" | "shared_bike" | "shared_scooter";
        /** VehicleProfile */
        VehicleProfile: {
            /**
             * Can Fold
             * @default false
             */
            can_fold: boolean;
            /** Height M */
            height_m?: number | null;
            /** @default none */
            kind: components["schemas"]["VehicleKind"];
            /** Weight T */
            weight_t?: number | null;
            /** Width M */
            width_m?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    data_status_v1_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatus"];
                };
            };
        };
    };
    list_favorites_v1_me_favorites_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_favorite_v1_me_favorites_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_favorite_v1_me_favorites__favorite_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                favorite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_v1_me_history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_v1_me_preferences_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_v1_me_preferences_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mobility_vehicles_v1_mobility_vehicles_get: {
        parameters: {
            query: {
                min_latitude: number;
                min_longitude: number;
                max_latitude: number;
                max_longitude: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_route_v1_routes_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reroute_v1_routes_reroute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query?: {
                q?: string;
                language?: components["schemas"]["Locale"];
                latitude?: number | null;
                longitude?: number | null;
                category?: string | null;
                bbox?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reverse_search_v1_search_reverse_get: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                language?: components["schemas"]["Locale"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
